### ISSUE TITLE
User can search their entries

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/code-journal#9]
## 💰 Motivation

Users can search for a specific entry.

## 📐 Plan

Create a search box that will return a list of entries that match the search term.

## ✅ Task List

- [x] Add a search box form to the header of the page
- [x] Add a `div[data-view="search-form"]` to the HTML.
- [ ] Add a form for entering a search term and returning matching entries to the `div[data-view="search-form"]`.
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Listen for `'submit'` events on the search entry form on the header of the page or the search box in the search form view and:
  - [ ] Switch to the search form view
  - [ ] Clear the header's search bar and pre-populate the search view's search box with the entered values
  - [ ] Put the form's input values into a new array.
  - [ ] Look through each entry's title and notes values for words that match the search terms.
  - [ ] Render the matching terms on the search form view.
- [ ] Reset the search form whenever the user switches views
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
